
trigger:
- master

pool:
  name: PrivatePool
  vmImage: ubuntu-latest

name: $(Build.SourceBranchName)_$(Build.BuildId)

stages:

  - stage: build
    dependsOn: []
    displayName: 'Run BUILD Pipeline'
    jobs:
      - template: build-pipeline.yaml
        parameters:
          Name: 'Environment Configuring'

  - stage: connectivity_check
    dependsOn: build
    displayName: 'Run HealthCheck Pipeline'
    jobs:
      - template: health_check.sh
        parameters:
          Name: 'HealthCheck'